# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Project page: https://app.readthedocs.org/projects/pydocs-translation-dashboard/

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  jobs:
    post_checkout: []
    install:
      - asdf plugin add uv
      - asdf install uv latest
    pre_build:
      - asdf global uv latest
    build:
      html:
        - uv run generate.py
        - mkdir -p _readthedocs/html
        - mv index.html style.css _readthedocs/html
