name: Dashboard PR preview
# Automatically edits a pull request's descriptions with a link
# to the GitHub pages PR preview.

on:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: chabroA/action-append-pr-description@v1.2.1
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          pr: ${{ github.event.number }}
          url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.ref_name }}"
          message: "📊 Dashboard preview:"
